/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        paper: 'var(--paper)',
        sunk: 'var(--paper-sunk)',
        lift: 'var(--paper-lift)',
        ink: 'var(--ink)',
        'on-ink': 'var(--on-ink)',
        soft: 'var(--ink-soft)',
        faint: 'var(--ink-faint)',
        ghost: 'var(--ink-ghost)',
        rule: 'var(--rule)',
        'rule-strong': 'var(--rule-strong)',
        navy: 'var(--navy)',
        'navy-deep': 'var(--navy-deep)',
        'navy-ring': 'var(--navy-ring)',
        blue: 'var(--blue)',
        'blue-hover': 'var(--blue-hover)',
        'blue-light': 'var(--blue-light)',
        'blue-lighter': 'var(--blue-lighter)',
        'blue-wash': 'var(--blue-wash)',
        'blue-wash-deep': 'var(--blue-wash-deep)',
        go: 'var(--go)',
        'go-wash': 'var(--go-wash)',
        warn: 'var(--warn)',
        'warn-wash': 'var(--warn-wash)',
        stop: 'var(--stop)',
        'stop-wash': 'var(--stop-wash)',
      },
      fontFamily: {
        display: 'var(--face)',
        sans: 'var(--face-ui)',
        mono: 'var(--face-mono)',
      },
      borderRadius: {
        xs: 'var(--r-xs)',
        sm: 'var(--r-sm)',
        DEFAULT: 'var(--r)',
        lg: 'var(--r-lg)',
        full: 'var(--r-round)',
      },
      boxShadow: {
        lift: 'var(--lift)',
        high: 'var(--lift-high)',
      },
      maxWidth: { page: 'var(--page)' },
      transitionTimingFunction: {
        out: 'var(--ease)',
        spring: 'var(--ease-spring)',
      },
      transitionDuration: {
        instant: 'var(--t-instant)',
        fast: 'var(--t-fast)',
        normal: 'var(--t-normal)',
      },
      animation: {
        'fade-in': 'fade-in var(--t-fast) var(--ease)',
        'rise-in': 'rise-in var(--t-normal) var(--ease)',
        'sheet-up': 'sheet-up var(--t-normal) var(--ease)',
        'pop-in': 'pop-in var(--t-fast) var(--ease)',
        'toast-in': 'toast-in var(--t-normal) var(--ease-spring)',
      },
    },
  },
  plugins: [],
};
