'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowUpRight, Download, Search, SlidersHorizontal } from 'lucide-react';

type Resource = { id:string; slug:string; title:string; description:string; file_size:number; downloads:number; thumbnail_url?:string|null; categories?:{name:string;slug:string}|null };
function formatSize(n:number){if(!n)return '—'; const u=['B','KB','MB','GB']; let i=0,x=n; while(x>=1024&&i<3){x/=1024;i++;} return `${x.toFixed(x>=10||i===0?0:1)} ${u[i]}`}
export default function Resources(){
 const [items,setItems]=useState<Resource[]>([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true);
 async function load(term=''){setLoading(true); const r=await fetch(`/api/resources?q=${encodeURIComponent(term)}`,{cache:'no-store'}); const j=await r.json(); setItems(j.resources??[]); setLoading(false)}
 useEffect(()=>{const p=new URLSearchParams(location.search); const term=p.get('q')??''; setQ(term); load(term)},[]);
 return <main><header className="site-header"><Link href="/" className="brand">CYRIQ<span>VFX</span></Link><nav><Link href="/resources">Resources</Link><Link href="/categories">Categories</Link></nav><Link href="/admin/login" className="creator-link">Creator Studio <ArrowUpRight size={15}/></Link></header><section className="container listing-head"><span className="kicker">LIBRARY</span><h1>Resources.</h1><p>Everything I release for editors, in one place. Free to download. No account required.</p><div className="library-tools"><form className="library-search" onSubmit={e=>{e.preventDefault();load(q)}}><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by title, type, or keyword"/><button>Search</button></form><button className="filter-btn"><SlidersHorizontal size={16}/> Filters</button></div></section><section className="container library-body">{loading?<div className="state">Loading resources…</div>:items.length===0?<div className="state"><h2>No resources yet.</h2><p>New uploads will appear here.</p></div>:<div className="resource-grid">{items.map(x=><article className="resource-card" key={x.id}><div className="resource-art">{x.thumbnail_url?<img src={x.thumbnail_url} alt=""/>:<span>CYRIQ / VFX</span>}</div><div className="resource-meta"><span>{x.categories?.name??'Resource'}</span><span><Download size={13}/>{x.downloads.toLocaleString()}</span></div><h3>{x.title}</h3><p>{x.description}</p><div className="card-foot"><span>{formatSize(x.file_size)}</span><Link href={`/download/${x.slug}`}>Download <ArrowUpRight size={14}/></Link></div></article>)}</div>}</section><footer className="footer container"><div className="brand">CYRIQ<span>VFX</span></div><small>Free resources for editors.</small></footer></main>;
}
